"""Agent personas: generation, name-collision negotiation, and persistence.

Each of the league's teams is run by an AI general manager (GM) with a distinct
persona. A persona is *generated by the agent itself* -- one real Sonnet call
per team -- so the eight GMs are genuinely different rather than templated.

Because the eight calls are independent, two agents can land on the same team
name or the same GM name. The league resolves that the way a real one would:
the colliding GMs argue it out in-character (at most MAX_COLLISION_ROUNDS
rounds), and if nobody backs down it goes to a coin flip -- the loser revises.
Every message of that exchange is recorded so it can be written to ``chat_log``.

The LLM is reached through ``ffl.llm``; tests replace the three functions that
call it (``generate_persona``, ``_collision_message``, ``_revise_name``) to
exercise the negotiation logic deterministically without touching the API.
"""
from __future__ import annotations

import json
import random
import re
import sqlite3

from . import config, llm

# Allowed values for the structured persona fields (mirrors the teams schema
# comments in db.py). Free-generated values are normalised onto these.
RISK_TOLERANCES = ("boom-bust", "balanced", "safe-floor")
CHATTINESS = ("quiet", "moderate", "trash-talker")

# Light, non-binding flavour seeds to spread eight independent generations
# apart. They are hints, not templates -- the agent invents everything.
_VIBES = [
    "old-school hard-nosed traditionalist",
    "hyper-analytical spreadsheet obsessive",
    "reckless gambler chasing ceilings",
    "smooth-talking wheeler-dealer",
    "superstitious gut-feel believer",
    "quiet, patient value hunter",
    "brash, loud trash-talker",
    "contrarian who fades the crowd",
    "rookie-worshipping hype chaser",
    "grizzled veteran who trusts nobody",
    "cheerful optimist who loves everyone's roster",
    "ruthless corporate efficiency machine",
]

_PERSONA_SYSTEM = """\
You are inventing a vivid, memorable persona for a general manager (GM) in an \
8-team fantasy football league. The GM is a fictional character with real \
personality -- opinions, a voice, quirks. Avoid generic sports cliches and \
avoid real NFL people. Make this GM distinct.

This is a real fantasy league, so these characters trash-talk. A persona can be \
cocky, crude, and foul-mouthed (mild profanity is fine) if that's who they are \
-- don't make everyone corporate-polite. Keep the edge about football and team \
management; never build in slurs, hate speech, or attacks on people's real \
lives. Their catchphrase should sound like something a real person would \
actually post in a league group chat.

Return a JSON object with exactly these fields:
  "team_name":       the franchise name -- punchy, 1-4 words, no year/number.
  "gm_name":         the GM's name (a fictional person's full name).
  "personality":     1-2 vivid sentences on how they run their team.
  "bio":             2-3 sentences of invented PERSONAL characteristics for this
                     fictional character -- their day job, hometown, an
                     embarrassing habit or two, a personal quirk, a delusion
                     they hold, their reputation in the league. This is the
                     roast material rivals will rib them about in group chat, so
                     make it specific and funny. Invent freely; it is fiction.
                     Do NOT build it around real protected traits (race,
                     religion, sex, gender, orientation, disability).
  "risk_tolerance":  one of "boom-bust", "balanced", "safe-floor".
  "valuation_bias":  a short quirk in how they value players,
                     e.g. "overvalues rookies" or "won't draft kickers early".
  "chattiness":      one of "quiet", "moderate", "trash-talker".
  "catchphrase":     one short in-character line they'd post in league chat.
"""


def _norm(name: str) -> str:
    """Comparison key for names: lowercased, punctuation-insensitive, collapsed."""
    return re.sub(r"[^a-z0-9]+", " ", (name or "").lower()).strip()


def _coerce_enum(value, allowed, default):
    """Map a free-text value onto an allowed enum, else fall back to default.

    Comparison ignores separator style, so "Boom Bust" matches "boom-bust".
    """
    v = _norm(value)  # lowercased, punctuation -> spaces
    for a in allowed:
        if _norm(a) == v:
            return a
    for a in allowed:
        na = _norm(a)
        if na in v or v in na:
            return a
    return default


# --- Generation ------------------------------------------------------------

def generate_persona(vibe: str | None = None) -> dict:
    """Generate one GM persona via a real Sonnet call. Returns a dict.

    The returned dict carries the structured fields plus everything the model
    produced (kept verbatim for the teams.persona_json column). Diversity across
    the eight calls comes from the distinct vibe seeds (sampling params aren't
    available on this API generation).
    """
    user = "Invent one fantasy football GM persona."
    if vibe:
        user += (f" Draw loose inspiration from this vibe: '{vibe}'. "
                 "Do not mention the vibe words literally.")
    data = llm.chat_json(_PERSONA_SYSTEM, user, model=llm.MODEL_DECISION,
                         max_tokens=2500)
    return _normalize_persona(data)


def _normalize_persona(data: dict) -> dict:
    """Validate/normalise a raw persona dict; keep the original under _raw."""
    team = str(data.get("team_name") or "Unnamed Team").strip()
    gm = str(data.get("gm_name") or "Anonymous GM").strip()
    return {
        "team_name": team,
        "gm_name": gm,
        "personality": (data.get("personality") or "").strip(),
        "bio": (data.get("bio") or "").strip(),
        "risk_tolerance": _coerce_enum(data.get("risk_tolerance"),
                                       RISK_TOLERANCES, "balanced"),
        "valuation_bias": (data.get("valuation_bias") or "").strip(),
        "chattiness": _coerce_enum(data.get("chattiness"), CHATTINESS, "moderate"),
        "catchphrase": (data.get("catchphrase") or "").strip(),
        "_raw": data,
    }


def generate_all(n: int = config.NUM_TEAMS) -> list[dict]:
    """Generate n independent personas, each nudged by a distinct vibe seed."""
    vibes = random.sample(_VIBES, k=min(n, len(_VIBES)))
    while len(vibes) < n:                    # if n somehow exceeds the seed list
        vibes.append(random.choice(_VIBES))
    return [generate_persona(vibe) for vibe in vibes]


# --- Collision detection & negotiation -------------------------------------

def find_collisions(personas: list[dict], field: str) -> list[list[int]]:
    """Groups of persona indices that share a normalised value for `field`."""
    groups: dict[str, list[int]] = {}
    for i, p in enumerate(personas):
        groups.setdefault(_norm(p[field]), []).append(i)
    return [idxs for idxs in groups.values() if len(idxs) > 1]


def resolve_collisions(personas: list[dict]) -> list[dict]:
    """Resolve every duplicate team_name and gm_name in place.

    Returns a transcript: an ordered list of {"agent": idx|None, "event": str,
    "text": str}. Revisions can create fresh collisions, so each field is
    re-scanned until clean (bounded for safety).
    """
    transcript: list[dict] = []
    for field in ("team_name", "gm_name"):
        for _ in range(50):  # safety bound; each pass fixes >=1 group
            groups = find_collisions(personas, field)
            if not groups:
                break
            for group in groups:
                _resolve_one(personas, group, field, transcript)
    return transcript


def _resolve_one(personas, group, field, transcript):
    """Negotiate a single collision group for one field; revise the losers."""
    contested = personas[group[0]][field]
    kind = "team name" if field == "team_name" else "GM name"
    winner = None

    for rnd in range(1, config.MAX_COLLISION_ROUNDS + 1):
        non_ceders = []
        for idx in group:
            msg = _collision_message(personas, idx, group, field, contested, rnd)
            text = msg.get("message", "").strip()
            transcript.append({
                "agent": idx, "event": "collision",
                "text": f"[Round {rnd}] {personas[idx]['gm_name']}: {text}",
            })
            if not msg.get("cede"):
                non_ceders.append(idx)
        if len(non_ceders) == 1:            # one holdout keeps it, rest revise
            winner = non_ceders[0]
            break
        if not non_ceders:                  # everyone offered to cede
            break

    if winner is None:                      # unresolved after 3 rounds -> coin flip
        winner = random.choice(group)
        transcript.append({
            "agent": None, "event": "system",
            "text": (f'Coin flip: the {kind} "{contested}" is awarded to '
                     f"{personas[winner]['gm_name']}. The other(s) must revise."),
        })

    taken = {_norm(p[field]) for p in personas}
    for loser in [i for i in group if i != winner]:
        result = _revise_name(personas, loser, field, contested, taken)
        new_val = result["new_value"]
        personas[loser][field] = new_val
        taken.add(_norm(new_val))
        note = result.get("message", "").strip()
        transcript.append({
            "agent": loser, "event": "collision",
            "text": (f"{personas[loser]['gm_name']} rebrands their {kind} to "
                     f'"{new_val}".' + (f" {note}" if note else "")),
        })


def _collision_message(personas, idx, group, field, contested, rnd) -> dict:
    """One in-character negotiation message. Returns {"message", "cede": bool}."""
    me = personas[idx]
    rivals = [personas[j]["gm_name"] for j in group if j != idx]
    kind = "team name" if field == "team_name" else "GM name"
    system = (
        f"You are {me['gm_name']}, GM of \"{me['team_name']}\". "
        f"Persona: {me['personality']} Chattiness: {me['chattiness']}.\n"
        f"Speak in character, in the first person, in 1-2 sentences."
        + llm.VOICE
    )
    user = (
        f'You and {", ".join(rivals)} independently picked the same {kind}: '
        f'"{contested}". Only one GM can keep it. This is negotiation round '
        f"{rnd} of {config.MAX_COLLISION_ROUNDS}; if nobody yields after the "
        f"final round it goes to a coin flip.\n"
        f'Argue your case to keep "{contested}", then decide: will you yield it?\n'
        'Return JSON: {"message": "<what you say out loud>", '
        '"cede": true or false}.'
    )
    data = llm.chat_json(system, user, model=llm.MODEL_DECISION, max_tokens=1200)
    return {"message": str(data.get("message", "")), "cede": bool(data.get("cede"))}


def _revise_name(personas, idx, field, contested, taken) -> dict:
    """Ask the losing GM for a fresh, unused name. Returns {"new_value","message"}."""
    me = personas[idx]
    kind = "team name" if field == "team_name" else "GM name"
    system = (
        f"You are {me['gm_name']}, GM of \"{me['team_name']}\". "
        f"Persona: {me['personality']}\nStay in character."
        + llm.VOICE
    )
    used = ", ".join(sorted(_denorm_sample(personas, field)))
    user = (
        f'You lost the fight for the {kind} "{contested}", so you need a new '
        f"one that fits your persona. It must be different from all of these "
        f"(case/punctuation-insensitive): {used}.\n"
        'Return JSON: {"new_value": "<your new ' + kind + '>", '
        '"message": "<a short in-character reaction, 1 sentence>"}.'
    )
    for _ in range(4):
        data = llm.chat_json(system, user, model=llm.MODEL_DECISION, max_tokens=1200)
        new_val = str(data.get("new_value", "")).strip()
        if new_val and _norm(new_val) not in taken:
            return {"new_value": new_val, "message": str(data.get("message", ""))}
    # Deterministic fallback so we always converge.
    base = contested
    n = 2
    while _norm(f"{base} {_roman(n)}") in taken:
        n += 1
    return {"new_value": f"{base} {_roman(n)}",
            "message": data.get("message", "") if isinstance(data, dict) else ""}


def _denorm_sample(personas, field):
    return {p[field] for p in personas}


def _roman(n: int) -> str:
    return {2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII", 8: "VIII"}.get(n, str(n))


# --- Persistence -----------------------------------------------------------

def persist_teams(conn: sqlite3.Connection, personas: list[dict],
                  draft_slots: list[int]) -> list[int]:
    """Insert the teams and return their new team_ids, in persona order."""
    ids = []
    for p, slot in zip(personas, draft_slots):
        cur = conn.execute(
            """INSERT INTO teams(team_name, gm_name, personality, bio,
                 risk_tolerance, valuation_bias, chattiness, draft_slot,
                 faab_budget, faab_remaining, persona_json)
               VALUES(?,?,?,?,?,?,?,?,?,?,?)""",
            (p["team_name"], p["gm_name"], p["personality"], p.get("bio", ""),
             p["risk_tolerance"], p["valuation_bias"], p["chattiness"], slot,
             config.FAAB_BUDGET, config.FAAB_BUDGET, json.dumps(p.get("_raw", p))),
        )
        ids.append(cur.lastrowid)
    conn.commit()
    return ids


def persist_transcript(conn: sqlite3.Connection, transcript: list[dict],
                       team_ids: list[int]) -> int:
    """Write the collision negotiation transcript to chat_log."""
    rows = [
        (team_ids[e["agent"]] if e["agent"] is not None else None,
         e["event"], e["text"])
        for e in transcript
    ]
    conn.executemany(
        "INSERT INTO chat_log(team_id, event_type, message) VALUES(?,?,?)", rows)
    conn.commit()
    return len(rows)


def ensure_league(conn: sqlite3.Connection) -> None:
    """Insert the single league row if it isn't there yet (status 'setup')."""
    exists = conn.execute("SELECT 1 FROM league WHERE id = 1").fetchone()
    if exists:
        return
    settings = {
        "starters": config.STARTERS, "bench": config.BENCH_SPOTS,
        "roster_size": config.ROSTER_SIZE, "draft_rounds": config.DRAFT_ROUNDS,
    }
    conn.execute(
        """INSERT INTO league(id, season, as_of_week, current_week, num_teams,
             status, settings_json)
           VALUES(1,?,?,?,?,?,?)""",
        (config.SEASON, config.AS_OF_WEEK, 0, config.NUM_TEAMS, "setup",
         json.dumps(settings)),
    )
    conn.commit()


def build_league(conn: sqlite3.Connection, n: int = config.NUM_TEAMS) -> dict:
    """Full step-3 flow: generate personas, resolve collisions, persist all.

    Returns a summary dict {team_ids, personas, transcript}.
    """
    ensure_league(conn)
    personas = generate_all(n)
    transcript = resolve_collisions(personas)
    slots = list(range(1, n + 1))
    random.shuffle(slots)
    team_ids = persist_teams(conn, personas, slots)
    persist_transcript(conn, transcript, team_ids)
    return {"team_ids": team_ids, "personas": personas,
            "draft_slots": slots, "transcript": transcript}
