"""Generate the league's 8 AI-GM personas and persist them.

Each team's persona is generated by a real Sonnet call; duplicate team/GM
names are negotiated in-character and the transcript is saved to chat_log.
This makes real Claude API calls -- ANTHROPIC_API_KEY must be set (env or .env).

Usage:
    python -m scripts.gen_personas [--db PATH] [--n 8] [--force]

--force regenerates even if teams already exist (this costs API calls).
"""
import argparse
import sys, os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ffl import backup, config, db, personas


def _preflight(dbp):
    """Integrity gate: verify the DB (restore from backup if corrupt) before use.
    Returns True to proceed, False to abort."""
    try:
        status = db.preflight(dbp)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        return False
    if status.startswith("restored:"):
        print(f"NOTE: database was corrupt on startup; restored from "
              f"{status.split(':', 1)[1]}")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=config.DB_PATH)
    ap.add_argument("--n", type=int, default=config.NUM_TEAMS)
    ap.add_argument("--force", action="store_true",
                    help="regenerate even if teams already exist")
    args = ap.parse_args()

    if not _preflight(args.db):
        return 1
    conn = db.init_db(args.db)
    existing = conn.execute("SELECT COUNT(*) FROM teams").fetchone()[0]
    if existing and not args.force:
        print(f"{existing} teams already exist in {args.db}. "
              "Re-run with --force to regenerate (this makes new API calls).")
        return 0
    if existing and args.force:
        conn.execute("DELETE FROM chat_log")
        conn.execute("DELETE FROM teams")
        conn.commit()
        print(f"Cleared {existing} existing teams and their chat log.")

    print(f"Generating {args.n} GM personas via {personas.llm.MODEL_DECISION} ...")
    result = personas.build_league(conn, n=args.n)

    print("\n=== League of 8 ===")
    for tid, p, slot in sorted(
            zip(result["team_ids"], result["personas"], result["draft_slots"]),
            key=lambda t: t[2]):
        print(f"  Pick {slot}: {p['team_name']}  --  GM {p['gm_name']} "
              f"[{p['risk_tolerance']}, {p['chattiness']}]")
        if p["personality"]:
            print(f"           {p['personality']}")

    n_coll = sum(1 for e in result["transcript"] if e["event"] != "system")
    if result["transcript"]:
        print(f"\n=== Name-collision negotiations ({len(result['transcript'])} "
              f"messages) ===")
        for e in result["transcript"]:
            print(f"  - {e['text']}")
    else:
        print("\nNo name collisions -- all 8 personas were distinct.")

    # Read back from chat_log to confirm persistence.
    logged = conn.execute(
        "SELECT COUNT(*) FROM chat_log WHERE event_type='collision' "
        "OR event_type='system'").fetchone()[0]
    print(f"\nPersisted {len(result['team_ids'])} teams; "
          f"{logged} negotiation messages written to chat_log.")

    # The personas are a non-reproducible, real-API creation (8 personas + any
    # negotiation transcript), so take an immediate backup -- this is also the
    # restore point that protects the gap before the draft runs.
    try:
        dest = backup.backup_db(db_path=args.db)
        if dest:
            print(f"Post-generation backup written: {dest}")
    except Exception as e:  # noqa: BLE001 -- report, don't fail a done creation
        print(f"WARNING: post-generation backup failed: {e}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
